### ISSUE TITLE
Xpress ignore LP warm starts

### ISSUE THREAD

**Issue by odow** [jump-dev/Xpress.jl#127]
It looks like it does, but I couldn't find any evidence these are actually passed to the solver
https://github.com/jump-dev/Xpress.jl/blob/e325c688e32ebe819cb4cb4db358635e0144f90a/src/MOI/MOI_wrapper.jl#L2866-L2886

Reported on Discourse: https://discourse.julialang.org/t/warmstarting-variables-does-not-work-with-xpress/60989

**Comment by henriquebecker91** [comment]
I would like to get this working as soon as possible. Someone has already tried something? Is there some hint from what is the source of the bug? I will probably work this weekend on this problem. I am almost sure the warm start is really being ignored because I currently warm start a model with a feasible solution of a subset of the model (a model with less columns) and the XPress spends hours without finding any feasible solution.

**Comment by metab0t** [comment]
https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSaddmipsol.html
I think this function can solve that issue. You need to pass the start value to Xpress solver with this function.

**Comment by henriquebecker91** [comment]
Before making the change, let me confirm if I understood correctly. The solution is to call the aforementioned XPRESS function inside [`MOI.optimize`](https://github.com/jump-dev/Xpress.jl/blob/e325c688e32ebe819cb4cb4db358635e0144f90a/src/MOI/MOI_wrapper.jl#L2312--L2380), before the actual solve, using the values saved in the `start` field of the Variable wrapper, correct?

Is the aforementioned XPRESS function already wrapped or do I need to write the CCall myself?

**Comment by metab0t** [comment]
You can write as follows:
```julia
function MOI.set( 
     model::Optimizer, 
     ::MOI.VariablePrimalStart, 
     x::MOI.VariableIndex, 
     value::Union{Nothing, Float64} 
 ) 
     info = _info(model, x)
     info.start = value
     if value !== nothing
         Xpress.addmipsol(model.inner, 1, [value], [info.column], C_NULL)
     end
     return 
 end
```

**Comment by henriquebecker91** [comment]
Created a PR (https://github.com/jump-dev/Xpress.jl/pull/148) to solve the problem. The solution is considerably more complex. Not only because I believe that `Xpress.addmipsol` does not work one-variable-at-time (I am almost sure it adds a whole solution, even if incomplete, each time; so each variable would be considered a distinct incomplete solution in your example.), but mainly because of another reasons discussed in the PR.

**Comment by joaquimg** [comment]
Since #148 MIP warmstart is accepted.

LP warmstart for xpress is harder because we need a basis (see https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSloadbasis.html)

**Comment by henriquebecker91** [comment]
If I can raise two questions:

1) Currently solving an LP multiple consecutive times (adding variables between solves) does reuse the previous base, right? At least this is my impression in practice.
2) Does JuMP have an API for LP warmstarts? Because `set_start_value` seems to be only for MIP-starts and I found nothing equivalent for LP.

**Comment by joaquimg** [comment]
Yes, xpress does re-use the last solution for LPs.

JuMP API for start values is not restricted to MIP by definition. Although it fits well on Xpress' mip start and fits poorly on xpress lp start because it would require converting the solution into a basis.
JuMP also accepts generic atributes if we want to pass something else useful.
