### ISSUE TITLE
Install Xpress in a cluster machine 

### ISSUE THREAD

**Issue by BastianMoya** [jump-dev/Xpress.jl#50]
The university's cluster has the software with the license and all things but I cannot install in Julia, all the time I have the next error message:

"Unable to locate Xpress installation, please check your environment variable XPRESSDIR . Note that Xpress must be obtained separately from fico.com"

I have set the environmental variable in the next ways:
ENV["XPRESSDIR"]="/usr/local/easybuild/software/Xpress/7.9/"
ENV["XPRESSDIR"]="/usr/local/easybuild/software/Xpress/7.9/lib"

They are not working. Someone has had the same problem?

**Comment by odow** [comment]
You probably need to set the environment variable on every node in the cluster (e.g., add it your bash settings so that it gets broadcast to all nodes on start-up).

We're not aware of any reason why it wouldn't work. I suggest you talk to your local IT. They probably have some things you need to do.

**Comment by joaquimg** [comment]
Closing due to staleness
