### ISSUE TITLE
Example with low-level C interface?

### ISSUE THREAD

**Issue by dpo** [jump-dev/Xpress.jl#87]
Could you show (in the README and/or tests) an example of passing a QP to Xpress using the low-level interface? Is it possible to pass entire matrices as with Gurobi.jl and CPLEX.jl? Thanks.

**Comment by joaquimg** [comment]
Since new release Gurobi.jl and CPLEX.jl followed Xpress.jl and a julian low level interface was removed.
Currently, all three packages only have two usage options:

- MathOptInterface (and consequently everything that uses MOI such as JuMP.jl and Convex.jl)
- a low level API which is basically just thin wrappers on ccall

What is you use case?
Some matrix interface are being develop in https://github.com/jump-dev/MatrixOptInterface.jl
